### ISSUE TITLE
SLS printing?

### ISSUE THREAD

**Issue by minystreem56** [Sillybutts/Alchemist#2]
Would I be able to print this with a SLS printer? I love the super nice finnish and having no supports.

**Comment by Sillybutts** [comment]
I have not looked into how SLS will work with stuff taking an impact. iirc, SLS tends to be more brittle? So stuff like the Sear, Plunger & PlungerRod, MagwellBack, and the BarTensioner might have issues with wear or breakage. So SLS is a "maybe?"

For Resin printing, Alchemist is pretty much a no-go. It'd be way too heavy, and resin prints would probably shatter.

**Comment by minystreem56** [comment]
Thanks!
