### ISSUE TITLE
Advice regarding Detent Block

### ISSUE THREAD

**Issue by CodebyADHawk** [Sillybutts/Alchemist#3]
I'm currently working on printing and building the Alchemist and I ran into an issue with fit of the detent ball into the detent block. For some reason, my printer elongated the circular hole for the detent slightly. It might have to do with print orientation and vibration - I'm not 100% sure. It seems a bit odd as other parts have printed well within tolerances. In the build video, I know you mentioned glue as an option of last resort. I was thinking of possibly trying to print the detent block at 99% scale to see if that might help. Do you see any potential issues with fitment of that part at 99%? Any other advice or pointers for this issue are also appreciated.

**Comment by Sillybutts** [comment]
99% should work. I am planning an update to the fileset this month that should fix the ball detent installation and some other things about the blaster. There's going to be another 4-40 screw that gets driven into the side of the detent to keep it in place, instead of relying on friction.
