### ISSUE TITLE
Skeggox_Buttplate_HORIZONTALPRINT STL file missing reinforcement bolt hole

### ISSUE THREAD

**Issue by CodebyADHawk** [Sillybutts/Alchemist#4]
Hi,

We discovered after printing the HORIZONTALPRINT version of the Skeggox buttplate that file seems to be missing the hole for the reinforcement bolt. Could you please review and update the file? The VERTICALPRINT STL seems to be correct.

**Comment by Sillybutts** [comment]
The horizontal print does not need the reinforcement bolt. The vertical print has it due to the weaker print orientation. Horizontal is plenty strong enough :)
